name: rstudio
base: core24
version: '2025.09.1-401'
license: AGPL-3.0
summary: Unofficial rstudio desktop snap
description: |
  A unofficial rstudio desktop snap
platforms:
  amd64:
grade: stable
confinement: classic
compression: lzo
apps:
  rstudio:
    command: rstudio --no-sandbox
    desktop: meta/gui/rstudio.desktop
parts:
  rstudio:
    plugin: dump
    source: https://download1.rstudio.org/electron/jammy/amd64/rstudio-${SNAPCRAFT_PROJECT_VERSION}-amd64-debian.tar.gz
    source-type: tar
    prime:
      - -chrome-sandbox
