name: rstudio
base: core24
version: '2025.05.1-513'
license: AGPL-3.0
summary: Unofficial rstudio desktop snap
description: |
  A unofficial rstudio desktop snap
platforms:
  amd64:
grade: stable
confinement: classic
compression: lzo
apps:
  rstudio:
    command: electron-launch $SNAP/rstudio --no-sandbox
    desktop: meta/gui/rstudio.desktop
parts:
  rstudio:
    plugin: dump
    source: https://download1.rstudio.org/electron/jammy/amd64/rstudio-${SNAPCRAFT_PROJECT_VERSION}-amd64-debian.tar.gz
    source-type: tar
    build-attributes:
      - enable-patchelf
    stage-packages:
      - libasound2t64
      - libatk-bridge2.0-0t64
      - libatk1.0-0t64
      - libatspi2.0-0t64
      - libcairo2
      - libcanberra-gtk3-module
      - libcups2t64
      # - libcurl3-gnutls
      # - libcurl3-nss
      - libcurl4t64
      - libdrm2
      - libgbm1
      - libgl1
      - libglu1-mesa
      - libglib2.0-0
      - libgtk-3-0t64
      - libibus-1.0-5
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libnspr4
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxext6
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxkbfile1
      - libxrandr2
      - libxss1
    prime:
      - -chrome-sandbox
      - -usr/share/icons
  electron-launch:
    after:
      - rstudio
    plugin: dump
    source: helper/
