name: Check upstream if a new version release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-upstream-changes:
    runs-on: ubuntu-latest
    steps:
      - name: fetch upstream latest tag
        id: upstream
        uses: oprypin/find-latest-tag@v1
        with:
          repository: rstudio/rstudio
        
      
      - run: echo "Upstream latest tag is ${{ steps.upstream.outputs.tag }}"
      
      - name: Checkout this repo
        uses: actions/checkout@v3
      
      - name: get current version
        id: current
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' snapcraft.yaml

      - run: echo "Snapcraft.yaml version is ${{ steps.current.outputs.result }}"


  update-snapcraft-yaml:
    if: check-upstream-changes.steps.upstream.outputs.tag != check-upstream-changes.steps.current.outputs.result
    runs-on: ubuntu-latest
    steps:
      - name: update version number  
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{upstream.tag}}"' 'snap/snapcraft.yaml'
          
      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "update snapcraft.yaml to version ${{check-upstream-changes.upstream.outputs.tag}}"
          git push
