name: Check upstream if a new version release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-upstream-changes:
    runs-on: ubuntu-latest
    steps:
      - name: fetch upstream latest tag
        id: upstream
        uses: oprypin/find-latest-tag@v1
        with:
          repository: rstudio/rstudio
      
      - name: Checkout this repo
        uses: actions/checkout@v4
      
      - name: get current version
        id: current
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' 'snap/snapcraft.yaml'

      - name: update version number
        if: steps.upstream.outputs.tag != steps.current.outputs.result
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.upstream.outputs.tag }}"' 'snap/snapcraft.yaml'
          
      - name: Commit changes
        if: steps.upstream.outputs.tag != steps.current.outputs.result
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "update snapcraft.yaml to version ${{ steps.upstream.outputs.tag }}"
          git push
